### ISSUE TITLE
Fail to load certain resources under HTTPS

### ISSUE THREAD

**Issue by yxdai-nju** [Brethland/Brethland.github.io#1]
When visiting your blog under HTTPS, my browser (Firefox 77) blocked resources from the [brethland.github.io](brethland.github.io) domain, because it redirects to [http://yuki.systems](http://yuki.systems), not [https://yuki.systems](https://yuki.systems), causing the page to load mixed contents..

Turing on “Enforce HTTPS” in your repository settings may help.

![Screenshot_2020-06-30 Brethland's Blog](https://user-images.githubusercontent.com/28209267/86122852-1041bf00-bb0b-11ea-89d2-a4297cb596aa.png)

**Comment by Brethland** [comment]
Fixed via minor changes, thanks for advising.
